/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Report, CityHealthSnapshot } from '../types';

// Default center coordinates: San Francisco area
export const DEFAULT_LAT = 37.7749;
export const DEFAULT_LNG = -122.4194;

export const INITIAL_REPORTS: Report[] = [
  {
    id: 'rep-1',
    imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=600&q=80',
    locationName: '1420 Market Street, San Francisco',
    latitude: 37.7752,
    longitude: -122.4190,
    issueType: 'pothole',
    severity: 'high',
    confidence: 'high',
    description: 'Deep, hazardous pothole in the middle lane causing cars to swerve dangerously.',
    publicSafetyRisk: 'High risk of tire damage and vehicle collisions due to swerving.',
    environmentalImpact: 'Negligible impact on surrounding vegetation.',
    recommendedAction: 'Cordon off lane and schedule rapid asphalt repair within 24 hours.',
    estimatedRepairUrgency: '24 hours',
    priorityScore: 82,
    affectedInfrastructure: 'road',
    suggestedDepartment: 'roads department',
    duplicateLikelihood: 'low',
    status: 'pending',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-2',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=600&q=80',
    locationName: '802 Mission Street, San Francisco',
    latitude: 37.7831,
    longitude: -122.4045,
    issueType: 'flooding',
    severity: 'critical',
    confidence: 'high',
    description: 'Major stormwater backup overflowing onto the sidewalk and flooding the local shop entrances.',
    publicSafetyRisk: 'Severe slip hazard for pedestrians; electrical risks for businesses.',
    environmentalImpact: 'Runoff carrying waste and oil into the city center water table.',
    recommendedAction: 'Dispatch storm drainage team to clear main lines immediately.',
    estimatedRepairUrgency: 'immediate',
    priorityScore: 95,
    affectedInfrastructure: 'drainage',
    suggestedDepartment: 'drainage department',
    duplicateLikelihood: 'low',
    status: 'in_progress',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-3',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=600&q=80',
    locationName: '220 Valencia Street, San Francisco',
    latitude: 37.7685,
    longitude: -122.4225,
    issueType: 'illegal_dumping',
    severity: 'medium',
    confidence: 'high',
    description: 'Several bags of industrial waste and broken furniture dumped next to the community garden.',
    publicSafetyRisk: 'Trip hazards and attraction of vermin/pests.',
    environmentalImpact: 'Contamination risk to garden soils and storm drains.',
    recommendedAction: 'Send bulky waste removal unit and log license plates if nearby camera footage exists.',
    estimatedRepairUrgency: '48 hours',
    priorityScore: 58,
    affectedInfrastructure: 'waste',
    suggestedDepartment: 'sanitation department',
    duplicateLikelihood: 'low',
    status: 'pending',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days ago
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-4',
    imageUrl: 'https://images.unsplash.com/photo-1509395062183-67c5ad6faff9?auto=format&fit=crop&w=600&q=80',
    locationName: '550 Castro Street, San Francisco',
    latitude: 37.7592,
    longitude: -122.4350,
    issueType: 'broken_streetlight',
    severity: 'medium',
    confidence: 'high',
    description: 'Entire row of three streetlights is completely black. The intersection is dangerously dark.',
    publicSafetyRisk: 'Increased likelihood of vehicle-pedestrian accidents and personal safety issues.',
    environmentalImpact: 'None.',
    recommendedAction: 'Dispatch maintenance technician to check regional ballast or bulb failures.',
    estimatedRepairUrgency: '7 days',
    priorityScore: 62,
    affectedInfrastructure: 'lighting',
    suggestedDepartment: 'electricity department',
    duplicateLikelihood: 'low',
    status: 'resolved',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-5',
    imageUrl: 'https://images.unsplash.com/photo-1584267326895-d889a5b15111?auto=format&fit=crop&w=600&q=80',
    locationName: '1100 Van Ness Avenue, San Francisco',
    latitude: 37.7850,
    longitude: -122.4215,
    issueType: 'water_leakage',
    severity: 'high',
    confidence: 'medium',
    description: 'High-pressure water main rupture under the sidewalk; water bubbling up rapidly.',
    publicSafetyRisk: 'Pedestrian sidewalk undermining and vehicle hydroplaning risks.',
    environmentalImpact: 'Millions of gallons of drinking water wasted; soil erosion.',
    recommendedAction: 'Emergency shut-off and isolation of main water loop for structural repair.',
    estimatedRepairUrgency: 'immediate',
    priorityScore: 89,
    affectedInfrastructure: 'water',
    suggestedDepartment: 'water department',
    duplicateLikelihood: 'low',
    status: 'in_progress',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), // 1 day ago
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  }
];

export const INITIAL_SNAPSHOTS: CityHealthSnapshot[] = [
  {
    id: 'snap-1',
    date: 'Day 1',
    overallHealth: 88,
    roadHealth: 90,
    drainageHealth: 92,
    wasteHealth: 85,
    lightingHealth: 88,
    waterHealth: 86,
    incidentCount: 5,
    resolvedCount: 2,
    highPriorityCount: 1,
    aiNarration: 'The city operations began the week with highly robust stats. Minor waste reports in the eastern sector were flagged, while general road health remained near peak values.'
  },
  {
    id: 'snap-2',
    date: 'Day 2',
    overallHealth: 85,
    roadHealth: 90,
    drainageHealth: 92,
    wasteHealth: 78,
    lightingHealth: 88,
    waterHealth: 80,
    incidentCount: 7,
    resolvedCount: 2,
    highPriorityCount: 2,
    aiNarration: 'Waste health dropped due to a newly reported illegal dumping site on Valencia Street. Additionally, water health showed decline after a major mains leakage was registered.'
  },
  {
    id: 'snap-3',
    date: 'Day 3',
    overallHealth: 81,
    roadHealth: 80,
    drainageHealth: 92,
    wasteHealth: 78,
    lightingHealth: 78,
    waterHealth: 80,
    incidentCount: 10,
    resolvedCount: 2,
    highPriorityCount: 3,
    aiNarration: 'Road health suffered a sharp 10% decrease following a series of high-severity pothole filings near Market St. Streetlighting also fell as row ballasts failed on Castro.'
  },
  {
    id: 'snap-4',
    date: 'Day 4',
    overallHealth: 75,
    roadHealth: 80,
    drainageHealth: 68,
    wasteHealth: 78,
    lightingHealth: 78,
    waterHealth: 72,
    incidentCount: 14,
    resolvedCount: 2,
    highPriorityCount: 5,
    aiNarration: 'An intense rainstorm triggered drainage crises, plunging drainage health to 68%. Blocked sewers reported on Mission St created significant sidewalk flooding.'
  },
  {
    id: 'snap-5',
    date: 'Day 5',
    overallHealth: 79,
    roadHealth: 80,
    drainageHealth: 76,
    wasteHealth: 78,
    lightingHealth: 88,
    waterHealth: 72,
    incidentCount: 15,
    resolvedCount: 3,
    highPriorityCount: 4,
    aiNarration: 'Streetlighting health rebounded back to 88% after emergency grid technicians replaced ballasts on Castro Street. Drainage crews began resolving low-level backups.'
  },
  {
    id: 'snap-6',
    date: 'Day 6',
    overallHealth: 81,
    roadHealth: 80,
    drainageHealth: 84,
    wasteHealth: 78,
    lightingHealth: 88,
    waterHealth: 80,
    incidentCount: 12,
    resolvedCount: 5,
    highPriorityCount: 2,
    aiNarration: 'Active municipal mobilization resulted in a general rise in City Health. Water engineers isolated the main leak on Van Ness, lifting the water score back to 80%.'
  },
  {
    id: 'snap-7',
    date: 'Day 7',
    overallHealth: 83,
    roadHealth: 82,
    drainageHealth: 88,
    wasteHealth: 78,
    lightingHealth: 88,
    waterHealth: 80,
    incidentCount: 10,
    resolvedCount: 6,
    highPriorityCount: 1,
    aiNarration: 'Today, overall city health settled at a solid 83%. Road repairs near main arterials and complete drain cleaning on Mission Street successfully contained major environmental hazards.'
  }
];
